project_id = "hdogwksrkopoprmhypvt"

[functions.ai-wedding]
verify_jwt = false

[functions.guestbook-moderate]
verify_jwt = false

[functions.generate-daily-reports]
verify_jwt = false

[functions.analyze-csv-import]
verify_jwt = false

[functions.analyze-wedding-theme]
verify_jwt = false
