import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.98.0";
import { uuidPattern } from "../_shared/guest-content-validation.ts";
const headers = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type" };
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { ...headers, "Content-Type": "application/json" } });
const hash = async (value: string) => Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)))).map((byte) => byte.toString(16).padStart(2, "0")).join("");
serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers });
  if (req.method !== "POST") return json({ error: "Method not allowed" }, 405);
  try { const { wedding_id, guest_session, file_name, mime_type, file_size } = await req.json(); if (typeof wedding_id !== "string" || !uuidPattern.test(wedding_id) || typeof guest_session !== "string" || guest_session.length < 16 || guest_session.length > 512 || typeof file_name !== "string" || file_name.length < 1 || file_name.length > 255 || mime_type !== "image/jpeg" || !Number.isInteger(file_size) || file_size <= 0 || file_size > 15 * 1024 * 1024) return json({ error: "Invalid memory upload" }, 400); const db = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!); const { data: session } = await db.from("guest_sessions").select("id").eq("wedding_id", wedding_id).eq("session_token_hash", await hash(guest_session)).is("revoked_at", null).gt("expires_at", new Date().toISOString()).maybeSingle(); if (!session) return json({ error: "Guest session expired" }, 401); const folder = `${wedding_id}/photos/${session.id}`; const { data: existing, error: listError } = await db.storage.from("wedding-assets").list(folder, { limit: 101, sortBy: { column: "created_at", order: "desc" } }); if (listError) return json({ error: "Could not check upload allowance" }, 503); const hourAgo = Date.now() - 60 * 60 * 1000; if ((existing || []).length >= 100 || (existing || []).filter(file => file.created_at && new Date(file.created_at).getTime() >= hourAgo).length >= 20) return json({ error: "Photo upload limit reached. Please try again later." }, 429); const path = `${folder}/${crypto.randomUUID()}.jpg`; const { data: signed, error } = await db.storage.from("wedding-assets").createSignedUploadUrl(path); if (error || !signed) return json({ error: "Could not authorize storage" }, 500); return json({ guest_session_id: session.id, storage_path: path, upload_token: signed.token }); } catch { return json({ error: "Unable to authorize upload" }, 500); }
});
