import { useEffect, useRef, useState, type CSSProperties, type ReactNode } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import { ArrowDownLeft, ArrowRight, ArrowUpRight, Bell, CalendarDays, Camera, Check, CheckCheck, ChevronLeft, ChevronRight, Clock3, Copy, Download, Flower2, Heart, Home, MapPin, MessageCircle, Music2, Plus, RotateCcw, Search, Send, Settings2, ShieldCheck, SlidersHorizontal, Sparkles, Users, Utensils, Wallet, X } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '@/components/ui/dialog';
import { categories, categoryColors, DEMO_KEY, demoPhoto, demoTotals, freshDemo, loadDemo, locations, money, weddingDate, type DemoGuest, type DemoState } from '@/lib/explore-demo';
import './Explore.css';

const routes = {
  guest: ['invitation', 'home', 'calendar', 'venue', 'rsvp', 'memories', 'updates', 'guestbook'],
  couple: ['home', 'guests', 'calendar', 'memories', 'updates', 'profile', 'budget'],
  management: ['home', 'guests', 'memories'],
};
type Role = keyof typeof routes;
type Sheet = 'share' | 'expense' | 'event' | 'profile' | 'report' | 'notifications' | 'reset' | 'credits' | null;
const coupleNav = [['home', Home, 'Home'], ['guests', Users, 'Guests'], ['calendar', CalendarDays, 'Calendar'], ['memories', Camera, 'Memories'], ['updates', MessageCircle, 'Updates'], ['profile', Heart, 'Profile']] as const;
const guestNav = [['home', Home, 'Home'], ['calendar', CalendarDays, 'Schedule'], ['venue', MapPin, 'Venue'], ['rsvp', Heart, 'RSVP'], ['memories', Camera, 'Memories'], ['updates', MessageCircle, 'Updates']] as const;
const managementNav = [['home', Home, 'Overview'], ['guests', Users, 'Guests'], ['memories', ShieldCheck, 'Moderation']] as const;
const id = () => crypto.randomUUID();

function Action({ children, onClick, className = '', ...props }: React.ButtonHTMLAttributes<HTMLButtonElement>) {
  return <button type="button" className={`ex-button ${className}`} onClick={onClick} {...props}>{children}</button>;
}
function IconButton({ label, children, onClick }: { label: string; children: ReactNode; onClick: () => void }) {
  return <button type="button" className="ex-icon" aria-label={label} title={label} onClick={onClick}>{children}</button>;
}

export default function Explore() {
  const [params, setParams] = useSearchParams();
  const requestedRole = params.get('role') || 'guest';
  const role: Role = Object.prototype.hasOwnProperty.call(routes, requestedRole) ? requestedRole as Role : 'guest';
  const requestedView = params.get('view') || (role === 'guest' ? 'invitation' : 'home');
  const view = routes[role].includes(requestedView) ? requestedView : routes[role][0];
  const [demo, setDemo] = useState<DemoState>(() => { try { return loadDemo(sessionStorage.getItem(DEMO_KEY)); } catch { return freshDemo(); } });
  const [sheet, setSheet] = useState<Sheet>(null);
  const [notice, setNotice] = useState('');
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState('All');
  const [photoId, setPhotoId] = useState<string | null>(null);
  const [reminderView, setReminderView] = useState(false);
  const [rsvpSaved, setRsvpSaved] = useState(false);
  const fileInput = useRef<HTMLInputElement>(null);
  const totals = demoTotals(demo);
  const visitor = demo.guests.find(g => g.id === 'visitor');
  const photos = demo.photos.filter(p => p.approved || role !== 'guest');
  const selectedPhoto = demo.photos.find(p => p.id === photoId);
  const nav = role === 'guest' ? guestNav : role === 'couple' ? coupleNav : managementNav;
  const pendingPhotos = demo.photos.filter(p => !p.approved).length;
  const confirmedParties = demo.guests.filter(g => g.status === 'Confirmed').length;
  const update = (fn: (current: DemoState) => DemoState) => setDemo(fn);
  const notify = (text: string) => setNotice(text);
  useEffect(() => { try { sessionStorage.setItem(DEMO_KEY, JSON.stringify(demo)); } catch { /* In-memory demo continues when storage is unavailable. */ } }, [demo]);
  useEffect(() => { if (!notice) return; const timer = setTimeout(() => setNotice(''), 7000); return () => clearTimeout(timer); }, [notice]);
  const go = (next: string, nextRole: Role = role) => { setParams({ role: nextRole, view: next }); setSheet(null); setRsvpSaved(false); setQuery(''); setFilter('All'); setNotice(''); window.scrollTo({ top: 0, behavior: 'instant' }); };
  const url = (target = 'invitation') => `${window.location.origin}/explore?role=guest&view=${target}`;
  async function copy(text: string) { try { await navigator.clipboard.writeText(text); notify('Link copied. Ready to share.'); } catch { setSheet('share'); notify('Select and copy the link below.'); } }
  function saveRsvp(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget);
    const guest: DemoGuest = { id: 'visitor', name: String(form.get('name')).trim(), status: String(form.get('response')) as DemoGuest['status'], party: Number(form.get('party')), meal: String(form.get('meal')), town: String(form.get('town')) };
    if (!guest.name) return;
    update(s => ({ ...s, guests: [...s.guests.filter(g => g.id !== 'visitor'), guest] })); setRsvpSaved(true);
  }
  async function upload(file?: File) {
    if (!file) return;
    if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type) || file.size > 1500000) { notify('Choose a JPG, PNG or WebP smaller than 1.5 MB for this demo.'); return; }
    if (demo.photos.length >= 8) { notify('This demo holds five uploaded photos. Reset it to try again.'); return; }
    const reader = new FileReader();
    reader.onload = () => { update(s => ({ ...s, photos: [{ id: id(), src: String(reader.result), caption: 'A moment to keep', by: visitor?.name || 'Demo guest', approved: false, liked: false }, ...s.photos] })); notify('Photo added to your demo session. Open Management → Moderation to approve it.'); };
    reader.onerror = () => notify('We could not read this photo. Please choose another.'); reader.readAsDataURL(file);
  }
  const label = (text: string) => <span className="ex-eyebrow">{text}</span>;
  const heading = (title: string, subtitle?: string, action?: ReactNode) => <header className="ex-heading"><div>{label(role === 'guest' ? `${demo.names} · ${demo.town}` : 'A little closer to your day')}<h1>{title}</h1>{subtitle && <p>{subtitle}</p>}</div>{action}</header>;
  const sectionTitle = (title: string, text?: string, onClick?: () => void) => <div className="ex-section-title"><h2>{title}</h2>{text && <button onClick={onClick}>{text}<ArrowUpRight size={15} /></button>}</div>;
  const statusBadge = (status: string) => <span className={`ex-badge ${status === 'Confirmed' || status === 'Published' ? 'lime' : status === 'Not sure' ? 'pink' : ''}`}>{status}</span>;
  const stats = <div className="ex-stat-grid"><div className="lime"><Users size={20} /><strong>{totals.confirmed}</strong><span>Guests coming</span></div><div className="pink"><Clock3 size={20} /><strong>{totals.waiting}</strong><span>Still deciding</span></div><div><Heart size={20} /><strong>{totals.declined}</strong><span>Unable to join</span></div></div>;
  const schedule = <div className="ex-agenda">{[...demo.events].sort((a, b) => a.time.localeCompare(b.time)).map((event, index) => <div className="ex-agenda-row" key={event.id}><time>{event.time}<span /></time><details className={`ex-event tone-${index % 3}`} open={index === 1}><summary><span>{index === 1 ? <Heart size={19} /> : index === 3 ? <Music2 size={19} /> : <CalendarDays size={19} />}{event.title}</span><ChevronRight size={17} /></summary><p><MapPin size={14} />{event.place}</p><p>{event.detail}</p></details></div>)}</div>;
  const updatesList = <div className="ex-feed">{demo.updates.map((item, index) => <article key={item.id}><div className="ex-person"><img src={demoPhoto} alt="" /><div><strong>{demo.names}</strong><span>{item.time} · Wedding update</span></div>{index === 0 && <span className="ex-dot" />}</div><p>{item.text}</p><span className="ex-feed-foot"><CheckCheck size={15} />Shared with your guests</span></article>)}</div>;
  const guestList = <><div className="ex-search"><Search size={18} /><input aria-label="Search guests" placeholder="Find someone in your guest list" value={query} onChange={e => setQuery(e.target.value)} /></div><div className="ex-filters">{['All', 'Confirmed', 'Not sure', 'Declined'].map(f => <button key={f} aria-pressed={filter === f} onClick={() => setFilter(f)}>{f}</button>)}</div><div className="ex-guests">{demo.guests.filter(g => (filter === 'All' || g.status === filter) && g.name.toLowerCase().includes(query.toLowerCase())).map((g, i) => <article key={g.id}><span className={`ex-initial tone-${i % 3}`}>{g.name.split(' ').map(n => n[0]).slice(0, 2).join('')}</span><div><strong>{g.name}</strong><p>{g.town} · {g.party} {g.party === 1 ? 'guest' : 'guests'}</p><small>{g.meal}</small></div><div className="ex-guest-status">{statusBadge(g.status)}{g.status === 'Not sure' && <button disabled={demo.reminders.includes(g.name)} onClick={() => { update(s => ({ ...s, reminders: [...s.reminders, g.name] })); notify(`Sample reminder for ${g.name} added to the guest inbox. No real message is sent.`); }}><Bell size={13} />{demo.reminders.includes(g.name) ? 'Reminded' : 'Remind'}</button>}</div></article>)}{!demo.guests.some(g => (filter === 'All' || g.status === filter) && g.name.toLowerCase().includes(query.toLowerCase())) && <p className="ex-empty">No guests match this search.</p>}</div></>;
  const memories = <><div className="ex-photo-summary"><span><Camera size={18} />{demo.photos.filter(p => p.approved).length} memories, one beautiful day</span><Action className="coral" onClick={() => fileInput.current?.click()}><Plus size={16} />Add photo</Action></div><input ref={fileInput} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e => { void upload(e.target.files?.[0]); e.target.value = ''; }} /><div className="ex-photo-grid">{photos.map((p, i) => <article key={p.id} className={i === 0 ? 'featured' : ''}><button className="ex-photo-open" onClick={() => setPhotoId(p.id)} aria-label={`Open ${p.caption}`}><img src={p.src} alt={p.caption} loading="lazy" /></button><div><span>{p.caption}<small>{p.by}{!p.approved ? ' · Awaiting approval' : ''}</small></span><IconButton label={p.liked ? 'Unlike photo' : 'Like photo'} onClick={() => update(s => ({ ...s, photos: s.photos.map(x => x.id === p.id ? { ...x, liked: !x.liked } : x) }))}><Heart size={18} fill={p.liked ? '#f5a5be' : 'none'} /></IconButton></div></article>)}</div><button className="ex-text-link" onClick={() => setSheet('credits')}>Photography from Unsplash<ArrowUpRight size={14} /></button></>;

  return <main className="explore-app">
    <Helmet><title>Explore a wedding | ForeverVow</title><meta name="description" content="Open an invitation, RSVP, explore a wedding budget and see how ForeverVow brings a Namibian wedding together. Try the interactive demo, then start your own." /></Helmet>
    <header className="ex-topbar"><Link className="ex-brand" to="/"><span><Heart size={19} fill="currentColor" /></span>ForeverVow</Link><div className="ex-top-actions"><span className="ex-demo-label"><i />Interactive demo</span><IconButton label="Share this demo" onClick={() => setSheet('share')}><Copy size={17} /></IconButton><Link className="ex-button coral ex-start" to="/couple-login">Start your wedding<ArrowUpRight size={16} /></Link></div></header>
    <div className="ex-layout"><aside className="ex-sidebar"><span className="ex-eyebrow">ONE WEDDING. EVERY PERSPECTIVE.</span><h2>Feel how it all<br />comes together.</h2><div className="ex-roles" aria-label="Choose an experience">{([['guest', Heart, 'Be our guest', 'The invitation, the RSVP, the day.'], ['couple', Users, 'Meet your wedding companion', 'Your people, plans and memories.'], ['management', ShieldCheck, 'Behind the celebration', 'A look at owner management.']] as const).map(([key, Icon, title, description], i) => <button key={key} aria-pressed={role === key} onClick={() => go(key === 'guest' ? 'invitation' : 'home', key)}><span className="ex-role-icon"><Icon size={19} /></span><span><small>0{i + 1}</small><strong>{title}</strong><em>{description}</em></span><ChevronRight size={15} /></button>)}</div><div className="ex-sidebar-bottom"><p><MapPin size={15} />A Namibian wedding story</p><p>This is a fictional wedding with sample details and illustrative photography. Everything you try stays in this demo session.</p><button className="ex-text-link" onClick={() => setSheet('reset')}><RotateCcw size={14} />Start the demo again</button></div></aside>
    <section className="ex-workspace" aria-label={`${role} experience`}>
      <div className="ex-context"><span>{role === 'guest' ? 'THE GUEST EXPERIENCE' : role === 'couple' ? 'YOUR WEDDING COMPANION' : 'OWNER PREVIEW'}</span><button onClick={() => setSheet('share')}>Guest RSVP link<ArrowUpRight size={14} /></button></div>
      {role !== 'guest' && <div className="ex-greeting"><div className="ex-person"><img src={demoPhoto} alt="" /><div><strong>{role === 'couple' ? demo.names : 'Hello, wedding host'}</strong><span>{demo.town}, Namibia</span></div></div><IconButton label="Open notifications" onClick={() => setSheet('notifications')}><Bell size={20} /><span className="ex-notification-dot" /></IconButton></div>}
      <div className={`ex-content ${view === 'invitation' ? 'invitation-view' : ''}`} key={`${role}-${view}`}>
      {role === 'guest' && <>
        {view === 'invitation' && <><section className="ex-invitation"><img src={demoPhoto} alt="Wedding couple photographed by Nathan Dumlao on Unsplash" fetchPriority="high" /><div className="ex-invite-top"><span><Heart size={16} />Together with our families</span><span>YOU'RE INVITED</span></div><div className="ex-invite-title"><p>A day for love. A place for you.</p><h1>{demo.names}</h1><div className="ex-invite-meta"><span><CalendarDays size={16} />{weddingDate(demo.date)}</span><span><MapPin size={16} />{demo.town}, Namibia</span></div><Action className="lime" onClick={() => go('home')}>Open our invitation<span className="ex-arrow-disc"><ArrowRight size={19} /></span></Action><button className="ex-invite-rsvp" onClick={() => go('rsvp')}>Already excited? RSVP here <ArrowUpRight size={15} /></button></div></section><div className="ex-invite-footer"><span>One invitation.<br /><strong>Every moment, together.</strong></span><button onClick={() => go('home', 'couple')}>See the couple's side<ArrowUpRight size={17} /></button></div></>}
        {view === 'home' && <><div className="ex-guest-hero"><img src={demoPhoto} alt="Wedding inspiration by Nathan Dumlao" /><div>{label('Our favourite people. Our favourite day.')}<h1>{demo.names}</h1><p>{weddingDate(demo.date)} · {demo.town}</p></div></div><div className="ex-rsvp-callout"><span className="ex-heart-disc"><Heart size={24} /></span><div><h2>{visitor ? `Thank you, ${visitor.name.split(' ')[0]}.` : 'A seat at our celebration.'}</h2><p>{visitor ? `Your response: ${visitor.status}` : 'We would love to know if you can join us.'}</p></div><Action className="lime" onClick={() => go('rsvp')}>{visitor ? 'Edit RSVP' : 'RSVP'}<ArrowRight size={16} /></Action></div><div className="ex-quick-grid"><button onClick={() => go('calendar')}><CalendarDays /><span>The day, planned<small>Welcome to the last dance</small></span><ArrowUpRight size={17} /></button><button onClick={() => go('venue')}><MapPin /><span>Meet us here<small>Acacia House · {demo.town}</small></span><ArrowUpRight size={17} /></button></div>{sectionTitle('A little note from us', 'All updates', () => go('updates'))}<article className="ex-note"><span className="ex-eyebrow">WITH LOVE, {demo.names.toUpperCase()}</span><p>{demo.updates[0]?.text}</p></article><button className="ex-wide-link" onClick={() => go('guestbook')}><MessageCircle />Leave a wish in our guestbook<ArrowUpRight size={19} /></button></>}
        {view === 'calendar' && <>{heading('Every moment of our day.', weddingDate(demo.date), <IconButton label="Save wedding date" onClick={() => {
          const day = demo.date.replace(/-/g, ''); const next = new Date(`${demo.date}T12:00:00Z`); next.setUTCDate(next.getUTCDate() + 1); const end = next.toISOString().slice(0,10).replace(/-/g, '');
          const calendar = `BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//ForeverVow//Demo//EN\r\nBEGIN:VEVENT\r\nUID:demo-wedding@forevervow\r\nDTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'')}\r\nDTSTART;VALUE=DATE:${day}\r\nDTEND;VALUE=DATE:${end}\r\nSUMMARY:ForeverVow demo wedding\r\nLOCATION:${demo.town} Namibia\r\nEND:VEVENT\r\nEND:VCALENDAR`;
          const href = URL.createObjectURL(new Blob([calendar], { type: 'text/calendar' })); const a = document.createElement('a'); a.href = href; a.download = 'forevervow-demo.ics'; a.click(); setTimeout(() => URL.revokeObjectURL(href), 1000);
        }}><Download size={20} /></IconButton>)}<div className="ex-date-banner"><span>{new Date(`${demo.date}T12:00:00`).toLocaleDateString('en-GB', { weekday: 'short' })}</span><strong>{demo.date.slice(8)}</strong><p>{new Date(`${demo.date}T12:00:00`).toLocaleDateString('en-GB', { month: 'long', year: 'numeric' })}<small>{demo.events.length} moments to look forward to · Namibia time</small></p></div>{schedule}</>}
        {view === 'venue' && <>{heading('A beautiful place to gather.', `${demo.town}, Namibia`)}<article className="ex-venue"><div className="ex-venue-icon"><MapPin size={34} /></div>{label('THE CELEBRATION')}<h2>Acacia House</h2><p>A garden ceremony, a golden-hour toast and an evening together in {demo.town}.</p><a className="ex-button lime" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(demo.town + ', Namibia')}`} target="_blank" rel="noreferrer">Explore {demo.town}<ArrowUpRight size={17} /></a><small>Illustrative venue. The map shows the city, not a booked wedding venue.</small></article>{sectionTitle('Before you arrive')}<div className="ex-practical"><article><Flower2 /><div><h3>Garden formal</h3><p>Dress up, feel comfortable. Bring a light layer for the evening.</p></div></article><article><Clock3 /><div><h3>A little early is lovely</h3><p>Welcome drinks from 15:00. The ceremony begins at 15:30.</p></div></article><article><Users /><div><h3>Coming from out of town?</h3><p>Keep your travel plans handy and let us know your dietary needs when you RSVP.</p></div></article></div></>}
        {view === 'rsvp' && <>{heading('Will you celebrate with us?', `${weddingDate(demo.date)} · ${demo.town}`)}{rsvpSaved ? <section className="ex-rsvp-success"><span className="ex-success-icon"><Check size={32} /></span><h2>{visitor?.status === 'Confirmed' ? 'Your seat is saved.' : 'Thank you for letting us know.'}</h2><p>{visitor?.name}, your demo response is now on the couple's guest list.</p><div className="ex-ticket"><Heart /><strong>{demo.names}</strong><p>{visitor?.party} {visitor?.party === 1 ? 'guest' : 'guests'} · {visitor?.meal}</p>{statusBadge(visitor?.status || '')}</div><Action className="lime" onClick={() => go('guests', 'couple')}>See it on the couple's side<ArrowRight size={17} /></Action><Action onClick={() => setRsvpSaved(false)}>Change my response</Action></section> : <form className="ex-form" onSubmit={saveRsvp}><fieldset className="ex-response"><legend>Your response</legend>{(['Confirmed', 'Not sure', 'Declined'] as const).map((value, i) => <label key={value}><input type="radio" name="response" value={value} required defaultChecked={visitor?.status === value || (!visitor && i === 0)} /><span>{i === 0 ? <Heart size={20} /> : i === 1 ? <Clock3 size={20} /> : <X size={20} />}{['Joyfully accept', 'Still deciding', 'Sadly decline'][i]}</span></label>)}</fieldset><label>Your name<input name="name" required maxLength={80} defaultValue={visitor?.name || ''} placeholder="e.g. Anna Shilongo" autoComplete="off" /></label><div className="ex-form-grid"><label>Guests in your party<select name="party" defaultValue={visitor?.party || 1}>{[1,2,3,4,5,6].map(n => <option key={n} value={n}>{n} {n === 1 ? 'guest' : 'guests'}</option>)}</select></label><label>Travelling from<select name="town" defaultValue={visitor?.town || 'Windhoek'}>{['Windhoek', 'Swakopmund', 'Walvis Bay', 'Rehoboth', 'Oshakati', 'Elsewhere'].map(t => <option key={t}>{t}</option>)}</select></label></div><label>Dietary preference<select name="meal" defaultValue={visitor?.meal || 'No preference'}>{['No preference', 'Vegetarian', 'Vegan', 'Gluten-free', 'Halal'].map(m => <option key={m}>{m}</option>)}</select></label><button className="ex-button coral" type="submit">Send my RSVP<Send size={17} /></button><p className="ex-fine">A practice RSVP for this fictional wedding. No real booking or message is sent.</p></form>}</>}
        {view === 'memories' && <>{heading('The moments between.', 'The photographs, the laughter, the memories you keep.')}{memories}<button className="ex-wide-link" onClick={() => go('guestbook')}><MessageCircle />Leave a little love<ArrowUpRight size={18} /></button></>}
        {view === 'updates' && <>{heading('A little closer to the day.')}<div className="ex-filters"><button aria-pressed={!reminderView} onClick={() => setReminderView(false)}>From the couple</button><button aria-pressed={reminderView} onClick={() => setReminderView(true)}>Reminders · {demo.reminders.length}</button></div>{reminderView ? <div className="ex-feed">{demo.reminders.length ? demo.reminders.map(name => <article key={name}><span className="ex-badge pink"><Bell size={13} />Demo reminder</span><h2>A little nudge, {name.split(' ')[0]}.</h2><p>We would love to know whether you can join our celebration. Your response helps us plan a wonderful day for everyone.</p><Action className="lime" onClick={() => go('rsvp')}>Respond to the invitation<ArrowRight size={17} /></Action></article>) : <div className="ex-empty"><Bell size={26} /><h2>All caught up.</h2><p>Try reminding an undecided guest from the couple's guest list. The sample notification will appear here.</p><Action onClick={() => go('guests', 'couple')}>Open guest list<ArrowRight size={17} /></Action></div>}</div> : updatesList}</>}
        {view === 'guestbook' && <>{heading('A little love, forever.', 'Leave a wish for the couple.')}<form className="ex-form" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); const name = String(f.get('name')).trim(), text = String(f.get('wish')).trim(); if (!name || !text) return; update(s => ({ ...s, wishes: [{ id: id(), name, text }, ...s.wishes] })); e.currentTarget.reset(); notify('Your wish is in the demo guestbook.'); }}><label>Your name<input name="name" maxLength={80} required defaultValue={visitor?.name || ''} placeholder="Your name" /></label><label>Your wish<textarea name="wish" required maxLength={500} placeholder="Here is to a lifetime of..." /></label><button type="submit" className="ex-button coral">Send your wishes<Heart size={17} /></button></form><div className="ex-wishes">{demo.wishes.map(w => <article key={w.id}><Heart size={17} /><p>{w.text}</p><strong>{w.name}</strong></article>)}</div></>}
      </>}
      {role === 'couple' && <>
        {view === 'home' && <>{heading('Your day. Coming together.', `${weddingDate(demo.date)} · ${demo.town}`)}<section className="ex-overview"><div><span className="ex-eyebrow">THE NEXT CHAPTER</span><h2>A little less planning.<br />A lot more looking forward.</h2><button onClick={() => setSheet('report')}>Your wedding at a glance<ArrowUpRight size={17} /></button></div><img src={demoPhoto} alt="Couple photographed by Nathan Dumlao" /></section><div className="ex-dashboard-grid"><article className="ex-readiness lime"><div className="ex-ring" style={{ '--progress': `${totals.readiness}%` } as CSSProperties}><strong>{totals.readiness}%</strong></div><div><h2>Wedding readiness</h2><p>{demo.tasks.filter(t => t.done).length} of {demo.tasks.length} details ready</p></div></article><button className="ex-metric cyan" onClick={() => go('guests')}><Users size={23} /><strong>{totals.confirmed}</strong><span>Guests saying yes<ArrowUpRight size={17} /></span></button></div>{sectionTitle('Your next little steps')}<div className="ex-checklist">{demo.tasks.filter(t => !t.done).length === 0 && <p><CheckCheck size={18} />All your demo details are ready.</p>}{demo.tasks.map(task => <label key={task.id}><input type="checkbox" checked={task.done} onChange={() => update(s => ({ ...s, tasks: s.tasks.map(t => t.id === task.id ? { ...t, done: !t.done } : t) }))} /><span>{task.title}</span>{task.done && <Check size={16} />}</label>)}</div><div className="ex-budget-peek"><Wallet /><div><span>Your wedding budget</span><strong>{money(Math.abs(totals.remaining))} {totals.remaining < 0 ? 'over budget' : 'left to spend'}</strong></div><IconButton label="Open budget" onClick={() => go('budget')}><ArrowUpRight size={21} /></IconButton></div>{sectionTitle('Your invitation', 'Share', () => setSheet('share'))}<button className="ex-wide-link" onClick={() => go('invitation', 'guest')}><Heart />See what your guests will see<ArrowUpRight size={18} /></button></>}
        {view === 'guests' && <>{heading('Your favourite people.', 'Every response, one less thing to chase.', <IconButton label="Share RSVP link" onClick={() => setSheet('share')}><Copy size={19} /></IconButton>)}{stats}{totals.waiting > 0 && <div className="ex-hint"><Bell size={19} /><p>{totals.waiting} invitations are still undecided. Give them a gentle nudge.</p><button onClick={() => setFilter('Not sure')}>View<ArrowRight size={15} /></button></div>}{guestList}</>}
        {view === 'calendar' && <>{heading('Make time for the moments.', weddingDate(demo.date), <IconButton label="Add event" onClick={() => setSheet('event')}><Plus size={22} /></IconButton>)}<div className="ex-date-banner"><CalendarDays size={27} /><p>Your wedding day<small>{demo.events.length} moments · All times in Namibia</small></p><span className="ex-badge lime">Planned</span></div>{schedule}</>}
        {view === 'memories' && <>{heading('Keep every little moment.', 'A shared album, full of your favourite people.')}{pendingPhotos > 0 && <div className="ex-hint"><Camera size={18} /><p>{pendingPhotos} new {pendingPhotos === 1 ? 'photo is' : 'photos are'} waiting for approval.</p><button onClick={() => go('memories', 'management')}>Review<ArrowRight size={15} /></button></div>}{memories}</>}
        {view === 'updates' && <>{heading('Everyone in the loop.', 'One message. Your whole celebration.')}<form className="ex-composer" onSubmit={e => { e.preventDefault(); const text = String(new FormData(e.currentTarget).get('message')).trim(); if (!text) return; update(s => ({ ...s, updates: [{ id: id(), text, time: 'Just now' }, ...s.updates] })); e.currentTarget.reset(); notify('Update shared in the demo. Open Guest → Updates to see it.'); }}><div><Send size={19} /><h2>A note to your guests</h2></div><label className="sr-only" htmlFor="demo-update">Message to guests</label><textarea id="demo-update" name="message" maxLength={1000} required placeholder="A change of plan? A little excitement? Share it here." /><footer><span>Visible on your invitation</span><button type="submit" className="ex-button">Post update<ArrowUpRight size={15} /></button></footer></form>{sectionTitle('Your shared updates', 'Guest view', () => go('updates', 'guest'))}{updatesList}</>}
        {view === 'profile' && <>{heading('Made for the two of you.')}<section className="ex-profile"><img src={demoPhoto} alt="Wedding portrait from Unsplash" /><div><span className="ex-badge lime">{demo.published ? 'Invitation published' : 'Invitation draft'}</span><h2>{demo.names}</h2><p>{weddingDate(demo.date)}<br />{demo.town}, Namibia</p><button className="ex-button" onClick={() => setSheet('profile')}>Make it yours<Settings2 size={16} /></button></div></section>{sectionTitle('Your wedding')}<div className="ex-settings">{[[Wallet, 'Wedding budget', `${money(demo.budget)} planned`, () => go('budget')], [Heart, 'Invitation & sharing', 'Your own little corner of the internet', () => setSheet('share')], [CalendarDays, 'Wedding details', 'Names, date and Namibian location', () => setSheet('profile')], [Bell, 'Notifications', 'The things that need your attention', () => setSheet('notifications')], [CheckCheck, 'Wedding summary', 'A clear view of what is ready', () => setSheet('report')]].map(([Icon, title, subtitle, action]) => { const I = Icon as typeof Heart; return <button key={String(title)} onClick={action as () => void}><span><I size={21} /></span><div><strong>{String(title)}</strong><small>{String(subtitle)}</small></div><ChevronRight size={17} /></button>; })}</div><div className="ex-conversion"><Heart size={26} /><h2>Imagine this with your names.</h2><p>Start your own wedding space and make every detail yours.</p><Link className="ex-button coral" to="/couple-login">Create our wedding<ArrowRight size={17} /></Link></div></>}
        {view === 'budget' && <>{heading('For everything you have planned.', 'Your wedding budget, in Namibian dollars.', <IconButton label="Edit wedding budget" onClick={() => setSheet('profile')}><SlidersHorizontal size={21} /></IconButton>)}<section className={`ex-budget-total ${totals.remaining < 0 ? 'over-budget' : ''}`}><div><span className="ex-eyebrow">{totals.remaining < 0 ? 'OVER YOUR BUDGET' : 'LEFT TO MAKE MEMORIES'}</span><strong>{money(Math.abs(totals.remaining))}</strong><p>{money(totals.spent)} spent of {money(demo.budget)}</p></div><div className="ex-budget-donut" style={{ background: `conic-gradient(${categoryColors.map((c, i) => { const start = demo.expenses.filter(e => categories.indexOf(e.category) < i).reduce((s,e) => s+e.amount,0) / Math.max(demo.budget, totals.spent) * 100; const end = start + demo.expenses.filter(e => e.category === categories[i]).reduce((s,e) => s+e.amount,0) / Math.max(demo.budget, totals.spent) * 100; return `${c} ${start}% ${end}%`; }).join(',')}, #333 0)` }}><div><Wallet size={26} /><span>{Math.round(totals.spent / demo.budget * 100)}% spent</span></div></div><Action className="coral" onClick={() => setSheet('expense')}><Plus size={18} />Record an expense</Action></section>{totals.remaining < 0 && <p className="ex-warning" role="status">You are {money(-totals.remaining)} over budget. Review your expenses or adjust your planned budget.</p>}{sectionTitle('Where it is going')}<div className="ex-categories">{categories.map((category, index) => { const sum = demo.expenses.filter(e => e.category === category).reduce((n,e) => n+e.amount,0); return <article key={category}><span className="ex-category-dot" style={{ background: categoryColors[index] }} /><div><strong>{category}</strong><span className="ex-category-track"><i style={{ width: `${Math.min(100, sum / Math.max(totals.spent,1) * 100)}%`, background: categoryColors[index] }} /></span></div><span><strong>{money(sum)}</strong><small>{Math.round(sum / Math.max(totals.spent,1) * 100)}% of spending</small></span></article>; })}</div>{sectionTitle('Recent expenses')}<div className="ex-transactions">{[...demo.expenses].reverse().map(e => <article key={e.id}><span className="ex-transaction-icon"><ArrowDownLeft size={18} /></span><div><strong>{e.name}</strong><small>{e.category}</small></div><b>{money(e.amount)}</b><IconButton label={`Remove ${e.name}`} onClick={() => update(s => ({ ...s, expenses: s.expenses.filter(x => x.id !== e.id) }))}><X size={15} /></IconButton></article>)}</div></>}
      </>}
      {role === 'management' && <>
        {view === 'home' && <>{heading('The care behind the celebration.', 'A sample of the owner workspace.')}<div className="ex-stat-grid"><div className="lime"><Heart size={21} /><strong>1</strong><span>Demo wedding</span></div><div className="cyan"><Users size={21} /><strong>{totals.confirmed}</strong><span>Guests confirmed</span></div><div><Camera size={21} /><strong>{pendingPhotos}</strong><span>Photos to review</span></div></div><article className="ex-managed-wedding"><img src={demoPhoto} alt="Wedding portrait from Unsplash" /><div>{statusBadge(demo.published ? 'Published' : 'Draft')}<h2>{demo.names}</h2><p>{weddingDate(demo.date)} · {demo.town}</p><div className="ex-inline-actions"><Action className="lime" onClick={() => go('home', 'couple')}>Open wedding<ArrowUpRight size={16} /></Action><Action onClick={() => { update(s => ({ ...s, published: !s.published })); notify(demo.published ? 'Demo invitation is now a draft. The guided preview stays available.' : 'Demo invitation marked as published.'); }}>{demo.published ? 'Set to draft' : 'Publish demo'}</Action></div></div></article>{sectionTitle('A little attention goes a long way')}<div className="ex-quick-grid"><button onClick={() => go('guests')}><Users /><span>Guest responses<small>{totals.waiting} still deciding</small></span><ArrowUpRight size={17} /></button><button onClick={() => go('memories')}><Camera /><span>Memory approval<small>{pendingPhotos ? `${pendingPhotos} waiting for you` : 'Everything reviewed'}</small></span><ArrowUpRight size={17} /></button></div><p className="ex-fine">Owner management is shown separately from couple accounts. All actions here affect only this fictional demo wedding.</p></>}
        {view === 'guests' && <>{heading('Every guest, accounted for.')}{stats}{guestList}</>}
        {view === 'memories' && <>{heading('A little care for every memory.', 'Approve guest contributions before they appear in the guest album.')}<div className="ex-moderation">{demo.photos.map(p => <article key={p.id}><img src={p.src} alt={p.caption} /><div><h2>{p.caption}</h2><p>{p.by}</p><span className={`ex-badge ${p.approved ? 'lime' : 'pink'}`}>{p.approved ? 'Approved' : 'Needs review'}</span><Action onClick={() => update(s => ({ ...s, photos: s.photos.map(x => x.id === p.id ? { ...x, approved: !x.approved } : x) }))}>{p.approved ? 'Hide from guests' : 'Approve photo'}<Check size={16} /></Action></div></article>)}</div></>}
      </>}
      {view !== 'invitation' && <footer className="ex-experience-footer"><span><i />Made for moments like these.</span><button onClick={() => go(role === 'guest' ? 'home' : 'invitation', role === 'guest' ? 'couple' : 'guest')}>{role === 'guest' ? 'Try the couple experience' : 'Open the guest invitation'}<ArrowRight size={16} /></button></footer>}
      </div>
      {view !== 'invitation' && <nav className={`ex-bottom-nav ${role === 'management' ? 'three' : ''}`} aria-label={`${role} demo navigation`}>{nav.map(([key, Icon, title]) => <button key={key} aria-current={view === key || (view === 'budget' && key === 'profile') ? 'page' : undefined} onClick={() => go(key)}><Icon size={21} /><span>{title}</span></button>)}</nav>}
    </section></div>
    {notice && <div className="ex-toast" role="status"><Check size={18} /><span>{notice}</span><button aria-label="Dismiss message" onClick={() => setNotice('')}><X size={17} /></button></div>}
    <Dialog open={!!sheet || !!photoId} onOpenChange={open => { if (!open) { setSheet(null); setPhotoId(null); } }}><DialogContent className="ex-modal"><DialogTitle>{photoId ? selectedPhoto?.caption : ({ share: 'One link. Everyone together.', expense: 'A little spending update.', event: 'Add a moment to the day.', profile: 'Make this wedding yours.', report: 'Your wedding at a glance.', notifications: 'Your little updates.', reset: 'Start fresh?', credits: 'The people behind the pictures.' }[sheet || ''] || '')}</DialogTitle><DialogDescription>{photoId ? 'Illustrative photography in your demo wedding album.' : 'Explore freely. Changes stay in this demo session.'}</DialogDescription>
      {selectedPhoto && <img className="ex-lightbox" src={selectedPhoto.src} alt={selectedPhoto.caption} />}
      {sheet === 'share' && <><div className="ex-share-link"><label>Guest invitation<input readOnly value={url()} onFocus={e => e.target.select()} /></label><Action onClick={() => void copy(url())}><Copy size={16} />Copy invitation</Action></div><div className="ex-share-link"><label>Direct guest RSVP<input readOnly value={url('rsvp')} onFocus={e => e.target.select()} /></label><Action className="lime" onClick={() => void copy(url('rsvp'))}><Copy size={16} />Copy RSVP link</Action></div><p className="ex-fine">These links open the sample wedding. Each visitor has their own demo session.</p></>}
      {sheet === 'expense' && <form className="ex-form" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); const amount = Number(f.get('amount')); const name = String(f.get('name')).trim(); if (!name || !Number.isFinite(amount) || amount <= 0) return; update(s => ({ ...s, expenses: [...s.expenses, { id: id(), name, amount, category: String(f.get('category')) as typeof categories[number] }] })); setSheet(null); notify('Expense recorded. Your remaining budget is updated.'); }}><label>What was it for?<input name="name" required maxLength={80} placeholder="e.g. Wedding rings" /></label><div className="ex-form-grid"><label>Amount (N$)<input name="amount" required type="number" min="0.01" max="10000000" step="0.01" placeholder="2500" /></label><label>Category<select name="category">{categories.map(c => <option key={c}>{c}</option>)}</select></label></div><button className="ex-button coral" type="submit">Save expense<Check size={17} /></button></form>}
      {sheet === 'event' && <form className="ex-form" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); const title = String(f.get('title')).trim(); if (!title) return; update(s => ({ ...s, events: [...s.events, { id: id(), title, time: String(f.get('time')), place: String(f.get('place')), detail: String(f.get('detail')) }] })); setSheet(null); notify('Moment added to both the couple calendar and guest schedule.'); }}><label>Moment title<input name="title" required maxLength={80} placeholder="Our first dance" /></label><div className="ex-form-grid"><label>Time in Namibia<input name="time" type="time" required defaultValue="19:30" /></label><label>Location<input name="place" required maxLength={80} defaultValue="The dining room" /></label></div><label>A little detail<textarea name="detail" maxLength={300} placeholder="What should guests know?" /></label><button className="ex-button coral" type="submit">Add to our day<Plus size={17} /></button></form>}
      {sheet === 'profile' && <form className="ex-form" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); const names = String(f.get('names')).trim(); const budget = Number(f.get('budget')); if (!names || budget <= 0) return; update(s => ({ ...s, names, budget, date: String(f.get('date')), town: String(f.get('town')) as typeof locations[number] })); setSheet(null); notify('Your sample wedding is updated across the demo.'); }}><label>Your names<input name="names" required maxLength={60} defaultValue={demo.names} /></label><div className="ex-form-grid"><label>Wedding date<input name="date" required type="date" defaultValue={demo.date} min="2026-01-01" max="2035-12-31" /></label><label>Location<select name="town" defaultValue={demo.town}>{locations.map(l => <option key={l}>{l}</option>)}</select></label></div><label>Wedding budget (N$)<input name="budget" type="number" required min="1" max="100000000" step="0.01" defaultValue={demo.budget} /></label><button className="ex-button coral" type="submit">Save wedding details<Check size={17} /></button></form>}
      {sheet === 'report' && <><div className="ex-report-stat"><span className="ex-eyebrow">{totals.readiness}% READY</span><h2>{totals.readiness === 100 ? 'Your details are in place.' : 'Your day is taking shape.'}</h2><p>{totals.confirmed} guests are confirmed across {confirmedParties} invitations. {totals.waiting} {totals.waiting === 1 ? 'invitation needs' : 'invitations need'} a follow-up.</p><p>{money(totals.spent)} of your {money(demo.budget)} budget has been recorded. {totals.remaining >= 0 ? `${money(totals.remaining)} remains.` : `You are ${money(-totals.remaining)} over budget.`}</p><p>{demo.events.length} moments are on the schedule. {demo.tasks.filter(t => !t.done).length} planning details remain.</p></div><Action className="lime" onClick={() => go('guests', 'couple')}>Check guest responses<ArrowRight size={17} /></Action></>}
      {sheet === 'notifications' && <div className="ex-notifications"><article><Users /><div><strong>{totals.waiting} invitations still deciding</strong><p>A gentle reminder could help you finalise your numbers.</p><button onClick={() => go('guests', 'couple')}>See guest list<ArrowRight size={15} /></button></div></article><article><Camera /><div><strong>{pendingPhotos ? `${pendingPhotos} memories to review` : 'Your shared album is ready'}</strong><p>Every contribution keeps a little piece of the day.</p><button onClick={() => go('memories', 'management')}>Open album review<ArrowRight size={15} /></button></div></article></div>}
      {sheet === 'reset' && <><p>Your practice RSVPs, photos and changes will be cleared from this demo session.</p><Action className="coral" onClick={() => { setDemo(freshDemo()); setPhotoId(null); go('invitation', 'guest'); notify('A fresh start. Welcome to the wedding.'); }}>Reset demo<RotateCcw size={17} /></Action></>}
      {sheet === 'credits' && <><p>Real photographs, licensed through Unsplash. The names, wedding and venue details in this demo are fictional; these photographs do not imply an endorsement or a ForeverVow client relationship.</p><a href="https://unsplash.com/photos/7baHM9rEYUw" target="_blank" rel="noreferrer">Nathan Dumlao · Main wedding portrait<ArrowUpRight size={15} /></a><a href="https://unsplash.com/photos/6X3c8kxj1Y8" target="_blank" rel="noreferrer">d i e g o Authentic · Celebration<ArrowUpRight size={15} /></a><a href="https://unsplash.com/photos/jKf0qVCLpfc" target="_blank" rel="noreferrer">Roma Shackiy · Together<ArrowUpRight size={15} /></a></>}
    </DialogContent></Dialog>
  </main>;
}
