import { useMemo, useState } from 'react';
import { Download, Plus, Trash2, Wallet } from 'lucide-react';
import { useQuery } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';

type Entry = { id: string; title: string; category: string; amount: number; spent_on: string; notes: string; receipt_url: string | null };
const money = (value: number, currency: string) => new Intl.NumberFormat(undefined, { style: 'currency', currency }).format(value);
export default function BudgetTracker({ weddingId, coupleNames, slug }: { weddingId: string; coupleNames: string; slug: string }) {
  const [adding, setAdding] = useState(false); const [busy, setBusy] = useState(false); const [planned, setPlanned] = useState('');
  const [form, setForm] = useState({ title: '', category: 'Venue', amount: '', spent_on: new Date().toISOString().slice(0, 10), notes: '' });
  const q = useQuery({ queryKey: ['budget', weddingId], enabled: weddingId !== 'preview-wedding', queryFn: async () => {
    const [budget, entries] = await Promise.all([supabase.from('wedding_budgets').select('*').eq('wedding_id', weddingId).maybeSingle(), supabase.from('wedding_budget_entries').select('*').eq('wedding_id', weddingId).order('spent_on', { ascending: false })]);
    if (budget.error || entries.error) throw budget.error || entries.error; setPlanned(String(budget.data?.planned_amount || '')); return { currency: budget.data?.currency || 'NAD', entries: (entries.data || []) as Entry[] };
  } });
  const data = q.data || { currency: 'NAD', entries: [] as Entry[] }; const spent = useMemo(() => data.entries.reduce((sum, entry) => sum + Number(entry.amount), 0), [data.entries]); const remaining = Number(planned || 0) - spent;
  const saveBudget = async () => { const amount = Number(planned); if (!Number.isFinite(amount) || amount < 0) return toast.error('Enter a valid budget.'); setBusy(true); const { error } = await supabase.from('wedding_budgets').upsert({ wedding_id: weddingId, planned_amount: amount, currency: data.currency }); setBusy(false); if (error) return toast.error('Budget could not be saved.'); toast.success('Budget updated.'); await q.refetch(); };
  const addEntry = async (event: React.FormEvent) => { event.preventDefault(); const amount = Number(form.amount); if (!form.title.trim() || !Number.isFinite(amount) || amount <= 0) return toast.error('Add a title and a positive amount.'); setBusy(true); const { error } = await supabase.from('wedding_budget_entries').insert({ wedding_id: weddingId, ...form, title: form.title.trim(), amount }); setBusy(false); if (error) return toast.error('Expense could not be added.'); setForm({ title: '', category: 'Venue', amount: '', spent_on: new Date().toISOString().slice(0, 10), notes: '' }); setAdding(false); await q.refetch(); };
  const remove = async (id: string) => { const { error } = await supabase.from('wedding_budget_entries').delete().eq('id', id).eq('wedding_id', weddingId); if (error) return toast.error('Expense could not be removed.'); await q.refetch(); };
  const download = () => { const lines = [`${coupleNames} budget report`, `Planned: ${money(Number(planned || 0), data.currency)}`, `Spent: ${money(spent, data.currency)}`, `Remaining: ${money(remaining, data.currency)}`, '', ...data.entries.map(entry => `${entry.spent_on} | ${entry.category} | ${entry.title} | ${money(Number(entry.amount), data.currency)}`)]; const url = URL.createObjectURL(new Blob([lines.join('\n')], { type: 'text/plain' })); const link = document.createElement('a'); link.href = url; link.download = `${slug}-budget-report.txt`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); };
  if (weddingId === 'preview-wedding') return <section className="rounded-[24px] bg-card p-4"><p className="text-sm text-muted-foreground">Budget tracking becomes available when you open your wedding workspace.</p></section>;
  return <section className="space-y-4 rounded-[26px] border border-border bg-card p-4 shadow-sm font-body">
    <div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><Wallet className="h-5 w-5" /><h2 className="text-xl font-semibold">Budget</h2></div><p className="mt-1 text-xs text-muted-foreground">Keep spending visible without connecting a bank account.</p></div><button aria-label="Add expense" onClick={() => setAdding(!adding)} className="grid h-11 w-11 place-items-center rounded-full bg-black text-white"><Plus className="h-4 w-4" /></button></div>
    <div className="grid grid-cols-3 gap-2"><div className="rounded-2xl bg-[#dff28e] p-3"><p className="text-[10px] text-muted-foreground">Planned</p><p className="mt-2 break-words text-sm font-semibold">{money(Number(planned || 0), data.currency)}</p></div><div className="rounded-2xl bg-muted p-3"><p className="text-[10px] text-muted-foreground">Spent</p><p className="mt-2 break-words text-sm font-semibold">{money(spent, data.currency)}</p></div><div className={`rounded-2xl p-3 ${remaining < 0 ? 'bg-[#ffd7d0]' : 'bg-[#d8eeec]'}`}><p className="text-[10px] text-muted-foreground">Remaining</p><p className="mt-2 break-words text-sm font-semibold">{money(remaining, data.currency)}</p></div></div>
    <div className="flex gap-2"><input aria-label="Total wedding budget" inputMode="decimal" value={planned} onChange={e => setPlanned(e.target.value)} placeholder="Total budget" className="min-h-11 min-w-0 flex-1 rounded-full border border-border px-4 text-sm" /><button disabled={busy} onClick={() => void saveBudget()} className="min-h-11 rounded-full bg-black px-4 text-xs font-semibold text-white disabled:opacity-50">Save</button><button aria-label="Download budget report" onClick={download} className="grid h-11 w-11 shrink-0 place-items-center rounded-full border border-border"><Download className="h-4 w-4" /></button></div>
    {adding && <form onSubmit={addEntry} className="space-y-3 rounded-3xl bg-muted p-4"><input required maxLength={200} placeholder="What was purchased?" value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} className="min-h-11 w-full rounded-xl border border-border px-3 text-sm" /><div className="grid grid-cols-2 gap-2"><select value={form.category} onChange={e => setForm({ ...form, category: e.target.value })} className="min-h-11 min-w-0 rounded-xl border border-border px-3 text-sm">{['Venue','Catering','Attire','Photography','Decor','Transport','Other'].map(value => <option key={value}>{value}</option>)}</select><input required type="number" min="0.01" step="0.01" placeholder="Amount" value={form.amount} onChange={e => setForm({ ...form, amount: e.target.value })} className="min-h-11 min-w-0 rounded-xl border border-border px-3 text-sm" /></div><input required type="date" value={form.spent_on} onChange={e => setForm({ ...form, spent_on: e.target.value })} className="min-h-11 w-full rounded-xl border border-border px-3 text-sm" /><textarea maxLength={2000} placeholder="Notes or receipt details" value={form.notes} onChange={e => setForm({ ...form, notes: e.target.value })} className="w-full rounded-xl border border-border p-3 text-sm" /><button disabled={busy} className="min-h-11 rounded-full bg-black px-5 text-sm font-semibold text-white">{busy ? 'Saving...' : 'Add expense'}</button></form>}
    {q.error ? <p role="alert" className="text-sm">Budget could not be loaded. <button className="underline" onClick={() => void q.refetch()}>Retry</button></p> : !data.entries.length ? <p className="py-3 text-sm text-muted-foreground">No expenses recorded yet.</p> : <ul className="divide-y divide-border">{data.entries.map(entry => <li key={entry.id} className="flex items-center justify-between gap-3 py-3"><div className="min-w-0"><p className="break-words text-sm font-medium">{entry.title}</p><p className="text-xs text-muted-foreground">{entry.category} · {entry.spent_on}</p></div><div className="flex items-center gap-2"><span className="text-sm font-semibold">{money(Number(entry.amount), data.currency)}</span><button aria-label={`Remove ${entry.title}`} onClick={() => void remove(entry.id)} className="grid h-9 w-9 place-items-center rounded-full text-muted-foreground"><Trash2 className="h-4 w-4" /></button></div></li>)}</ul>}
  </section>;
}
